# .github/ISSUE_TEMPLATE/config.yml
blank_issues_enabled: false
contact_links:
  - name: ðŸ“š Documentation
    url: https://github.com/fab1o/pimp-my-shell/blob/main/doc/index.md
    about: Read our docs before submitting issues.
